[build]
	publish = "html/"

[[redirects]]
	from = "https://hovelo.co.uk"
	to = "https://www.hovelo.co.uk"
	status = 301

[[redirects]]
	from = "/mail"
	to = "https://accounts.zoho.eu/signin"
	status = 301
