[build]
	publish = "html/"

[[headers]]
	# Define which paths this specific [[headers]] block will cover.
	for = "/*"
	
	[headers.values]
		Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
